name: /dam/dev
description: a blog about my developer adventures
meta_description: "a blog about my developer adventures"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://damsonn.github.io'

# Details for the RSS feed generator
url:            'http://damsonn.github.io'
author:         'Damien Dormal'

google_analytics: 'UA-40663494-2'
# Social
disqus_short_name: damdev
linkedin_user: damiendormal
github_user: damsonn