name: /dam/dev
description: a blog about my developer adventures
meta_description: "a blog about my developer adventures"

gems:
  - jekyll-sitemap

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://damdev.me'

# Details for the RSS feed generator
url:            'http://damdev.me'
author:         'Damien Dormal'

google_analytics: 'UA-40663494-2'
# Social
email: dormal.damien@gmail.com
disqus_short_name: damdev
linkedin_user: damiendormal
github_user: damsonn
twitter_user: DamienDormal
